dat<-read.csv('out/allLongitudinal.csv',stringsAsFactors=FALSE)
dat$pTime<-apply(dat[,c('pat','time')],1,paste,collapse=' ')
bulkTimes<-unique(dat[dat$bulk,'pTime'])
bulkTimes<- bulkTimes[bulkTimes%in% dat[!dat$bulk,'pTime']]
thisDat<-dat[dat$pTime %in% bulkTimes,]
pos<-structure(1:length(bulkTimes),.Names=bulkTimes)
ylabA<-expression('IFN'*alpha*'2 IC'[50]*' (pg/ml)')
ylabB<-expression('IFN'*beta*' IC'[50]*' (pg/ml)')
meanA<-tapply(thisDat[!thisDat$bulk,'ic50'],thisDat[!thisDat$bulk,'pTime'],function(xx)exp(mean(log(xx),na.rm=TRUE)))
meanB<-tapply(thisDat[!thisDat$bulk,'beta'],thisDat[!thisDat$bulk,'pTime'],function(xx)exp(mean(log(xx),na.rm=TRUE)))
meanA_bulk<-tapply(thisDat[thisDat$bulk,'ic50'],thisDat[thisDat$bulk,'pTime'],function(xx)exp(mean(log(xx),na.rm=TRUE)))
meanB_bulk<-tapply(thisDat[thisDat$bulk,'beta'],thisDat[thisDat$bulk,'pTime'],function(xx)exp(mean(log(xx),na.rm=TRUE)))
pdf('out/bulk_vs_single.pdf',height=6,width=8,useDingbats=FALSE)
layout(matrix(1:4,nrow=2),width=c(1,.72))
  par(mar=c(4.1,4.9,.1,.4),lheight=1.1)
  for(ifn in c('ic50','beta')){
    spreadX<-vipor::offsetX(pos[thisDat$pTime],thisDat$bulk,width=.07)
    plot(pos[thisDat$pTime]+.15*(thisDat$bulk*2-1)+ifelse(thisDat$bulk,0,spreadX),thisDat[,ifn],log='y',yaxt='n',bg=ifelse(thisDat$bulk,'#FF000088','#0000FF33'),ylab=ifelse(ifn=='ic50',ylabA,ylabB),xlab='',xaxt='n',pch=ifelse(thisDat$bulk,22,21),cex=1.2,mgp=c(3,.9,0),xlim=c(min(pos)-.5,max(pos)+.5),xaxs='i')
    dnar::logAxis(las=1)
    for(ii in 1:length(pos))axis(1,pos[ii],sub('.* +','\n',names(pos))[ii],tcl=0,mgp=c(3,1.3,0))
    for(ii in unique(sub(' .*$','',names(pos)))){
      thisPos<-pos[grep(ii,names(pos))]
      axis(1,mean(thisPos),sprintf('%s\n',ii),tcl=0,mgp=c(3,1.3,0))
      segments(min(thisPos)-.2,dnar::convertLineToUser(.7),mean(thisPos)-.61,dnar::convertLineToUser(.7),xpd=NA)
      segments(max(thisPos)+.2,dnar::convertLineToUser(.7),mean(thisPos)+.61,dnar::convertLineToUser(.7),xpd=NA)
      if(ii=='MM39')abline(v=c(min(thisPos)-.5,max(thisPos)+.5))
    }
    abline(v=pos[-1]-.5,col='#00000022')
    text(dnar::convertLineToUser(.2,2),dnar::convertLineToUser(.7),'Participant:',xpd=NA,adj=1,cex=1.05)
    text(dnar::convertLineToUser(.2,2),dnar::convertLineToUser(1.8),'DFOSx:',xpd=NA,adj=1,cex=1.02)
  }
#dev.off()
#pdf('out/bulk_vs_singleMean.pdf',height=5,width=10)
  par(mar=c(4.1,4.7,.1,.1),lheight=1.1)
  plot(meanA[thisDat[thisDat$bulk,'pTime']],thisDat[thisDat$bulk,'ic50'],log='xy',ylab=expression('IFN'*alpha*'2 IC'[50]*' of bulk isolate (pg/ml)'),xaxt='n',yaxt='n',pch=21,bg='#00000033',xlim=range(thisDat$ic50,na.rm=TRUE),ylim=range(thisDat$ic50,na.rm=TRUE),cex=1.2,xlab='',mgp=c(2.2,1,0))
  title(xlab=expression('Mean IFN'*alpha*'2 IC'[50]*' of corresponding'),mgp=c(1.8,1,0))
  title(xlab=expression('single isolates (pg/ml)'),mgp=c(2.7,1,0))
  dnar::logAxis(las=1,mgp=c(3,.65,0))
  dnar::logAxis(1,mgp=c(3,.6,0))
  abline(0,1,lty=2)
  plot(meanB[thisDat[thisDat$bulk,'pTime']],thisDat[thisDat$bulk,'beta'],log='xy',ylab=expression('IFN'*beta*' IC'[50]*' of bulk isolate (pg/ml)'),xaxt='n',yaxt='n',pch=21,bg='#00000033',ylim=range(thisDat$beta,na.rm=TRUE),xlim=range(thisDat$beta,na.rm=TRUE),cex=1.2,xlab='',mgp=c(2.2,1,0))
  title(xlab=expression('Mean IFN'*beta*' IC'[50]*' of corresponding'),mgp=c(1.8,1,0),adj=.4)
  title(xlab=expression('single isolates (pg/ml)'),mgp=c(2.7,1,0),adj=.4)
  dnar::logAxis(las=1,mgp=c(3,.65,0))
  dnar::logAxis(1,mgp=c(3,.6,0))
  abline(0,1,lty=2)
  text(grconvertX(.0001,from='ndc'),grconvertY(0.997,from='ndc'),'A',xpd=NA,adj=c(0,1),cex=2)
  text(grconvertX(.005,from='nfc'),grconvertY(0.997,from='ndc'),'C',xpd=NA,adj=c(0,1),cex=2)
  text(grconvertX(.0001,from='ndc'),grconvertY(0.997,from='nfc'),'B',xpd=NA,adj=c(0,1),cex=2)
  text(grconvertX(.005,from='nfc'),grconvertY(0.997,from='nfc'),'D',xpd=NA,adj=c(0,1),cex=2)
dev.off()
file.copy('out/bulk_vs_single.pdf','out/Fig._S4.pdf',overwrite=TRUE)


cor(log(meanA[thisDat[thisDat$bulk,'pTime']]),log(thisDat[thisDat$bulk,'ic50']))
cor(log(meanB[thisDat[thisDat$bulk,'pTime']]),log(thisDat[thisDat$bulk,'beta']))
cor(log(meanA),log(meanA_bulk[names(meanA)]))
cor(log(meanB),log(meanB_bulk[names(meanB)]))

